export const CONSTANTES_APP = {
    FORMATO_PENA: 'NATURAL',
    FORMATO_PEJU: 'JURIDICA',
    FORMATO_PERSONA_NATURAL: 'VINCULACION_PERSONA_NATURAL',
    FORMATO_PERSONA_JURIDICA: 'VINCULACION_PERSONA_JURIDICA',
    ETIQUETA_FORMATO_LOGO: 'LOGO',
    ETIQUETA_FORMATO_CODIGO: 'CODIGO',
    ETIQUETA_FORMATO_VERSION: 'VERSION',
    ETIQUETA_FORMATO_TITULO: 'TITULO',
    ETIQUETA_FORMATO_TEXTO_UNO: 'TEXTO_UNO',
    ETIQUETA_FORMATO_TEXTO_DOS: 'TEXTO_DOS',
    ETIQUETA_FORMATO_TEXTO_TRES: 'TEXTO_TRES',
    ETIQUETA_FORMATO_TEXTO_CUATRO: 'TEXTO_CUATRO',

    STRING_SI: 'SI',
    STRING_NO: 'NO',

    TIEM_ID_OTRO_TIPO_EMPRESA: 'f7919666-dd5b-4097-8f86-382216b46339',

    /*  CONSTANTES DE ARCHIVOS */
    TAMANO_ARCHIVO_PERMITIDO: 1024000
}